/*
 * generated by Xtext
 */
package diagnosis.it3.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDiagUiModule extends diagnosis.it3.mydsl.ui.AbstractMyDiagUiModule {
	public MyDiagUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	/*Stablishes Styles*/
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
		 return DefaultHighlightingConfiguration.class;
	}
	
	/*Associates styles to elements*/
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingConfiguration () {
		 return DefaultHighlightingCalculator.class;
	}

}
