/*
 * generated by Xtext
 */
package diagnosis.it3.mydsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import diagnosis.it3.mydsl.ui.internal.MyDiagActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDiagExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MyDiagActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MyDiagActivator.getInstance().getInjector(MyDiagActivator.DIAGNOSIS_IT3_MYDSL_MYDIAG);
	}
	
}
