/*
* generated by Xtext
*/
package diagnosis.it3.mydsl.ui.labeling

import com.google.inject.Inject
import diagnosis.Diagnosis
import diagnosis.PatientData
import diagnosis.Variations
import diagnosis.Annotation
import diagnosis.GeneF
import diagnosis.PredictionF
import diagnosis.EffectF
import diagnosis.ScoreF
import diagnosis.Vcf
import diagnosis.Report
import diagnosis.ReportVariations
import diagnosis.HgvsS
import diagnosis.MAFF
import diagnosis.Order

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
class MyDiagLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {

	@Inject
	new(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	def text(Diagnosis filter){
		'Diagnosis'
	}
	
	//Patient Data
	def text(PatientData patient){
		'Read'
	}
	
	def text(Variations variations){
		'Variations'
	}
	
	def text(Vcf variations){
		'VCF'
	}
	
	//Analysis
	def text(Annotation variations){
		'Annotate'
	}
	
	def text(HgvsS hgvs){
		'Search by hgvs '
	}
	def text(GeneF gene){
		'Filter by Gene'
	}
	
	def text(MAFF maf){
		if (maf.order==null) 'Filter by MAF'
		else 'Prioritize by MAF'
	}
			
	def text(EffectF prediction){
		if (prediction.order==null) 'Filter by '+prediction.algorithm +' effect'
		else 'Prioritize by '+prediction.algorithm +' effect'
	}
	
	def text(ScoreF prediction){
		if (prediction.order==null) 'Filter by '+prediction.algorithm +' score'
		else 'Prioritize by '+prediction.algorithm +' score'
	}
	
	def text(Order order){
		'Order criteria'
	}
	
	//Report
	def text(Report report){
		'Report'
	}
	
	def text(ReportVariations report){
		'Variations'
	}
	
//	def text(Greeting ele) {
//		'A greeting to ' + ele.name
//	}
//
//	def image(Greeting ele) {
//		'Greeting.gif'
//	}
}
