/**
 * generated by Xtext
 */
package diagnosis.it3.mydsl.ui.outline;

import diagnosis.Diagnosis;
import diagnosis.PatientData;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class MyDiagOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public String text_Diagnosis(final Diagnosis filter) {
    return "Diagnosis";
  }
  
  public String text_PatientData(final PatientData filter) {
    return "Read";
  }
}
