/*
 * generated by Xtext
 */
package diagnosis.it3.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDiagRuntimeModule extends diagnosis.it3.mydsl.AbstractMyDiagRuntimeModule {

}
