/*
* generated by Xtext
*/
package diagnosis.it3.mydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyDiagStandaloneSetup extends MyDiagStandaloneSetupGenerated{

	public static void doSetup() {
		new MyDiagStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

