/*
* generated by Xtext
*/
package diagnosis.it3.mydsl.ui.outline

import diagnosis.Diagnosis
import diagnosis.PatientData

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class MyDiagOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {
	def text_Diagnosis(Diagnosis filter){
		'Diagnosis'
	}
	
	def text_PatientData(PatientData filter){
		'Read'
	}
}
