/*
 * generated by Xtext
 */
package diagnosis.it3.mydsl.ui.contentassist

import diagnosis.it3.mydsl.ui.contentassist.AbstractMyDiagProposalProvider


/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyDiagProposalProvider extends AbstractMyDiagProposalProvider {
	
}
